version: '3'

services:
  web:
    build: .
    command: ./start.sh
    ports:
      - "8080:8080"
    environment:
      - DEBUG_MODE=true
      - SERVER_FQDN=${SERVER_HOSTNAME}.${SERVER_DOMAIN}
      - DBPASS=${DATABASE_PASSWORD}
      - DBUSER=${DATABASE_USER}
      - DBHOST=${DATABASE_HOSTNAME}
      - DBNAME=${DATABASE_NAME}
    volumes:
      - ./:/code
      - ${VOLUMES_ROOT_PATH}/thundercloud/config:/code/thundercloud/config
      - ${VOLUMES_ROOT_PATH}/thundercloud/media:/data
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    hostname: ${DATABASE_HOSTNAME}
    container_name: postgresql
    restart: ${RESTART_MODE}
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${VOLUMES_ROOT_PATH}/postgresql/data:/var/lib/postgresql/data
